### ISSUE TITLE
פיתוח - ממשק מורה - יעדים

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#39]
אפשרות למורה לשבץ יעדים ספציפיים לתלמידים או יעד כיתתי דרך ממשק המורה

**Comment by Hermoni** [comment]
יש בעיה עם שיבוץ יעדים לכל הכיתה כאשר בוחרים את "בחר את כולם". בחלק מהמורים זה עובד תקין ובחלק לא
דוגמא ליוזר תקין - meira.hebkhan
דוגמא ליוזר בעייתי - elena.hebkhan
לשתיהן אותו סיסמא - khan2014
בנוסף, לפעמים מקבלים מסך אפור בלי אפשרות ללחוץ על כולם. לא הצלחתי לעלות על דפוס שמוביל לזה אבל תנסה לשבץ יעדים דרך המשתמש הבעייתי ואולי זה יקרה גם לך.

**Comment by koreno** [comment]
מה בדיוק קורה כשזה "לא עובד תקין"?

**Comment by Hermoni** [comment]
כלום.
זה חוזר למסך הראשי בלי שהוא שיבץ יעדים לאף אחד.
אגב, זה לפעמים קורה גם אצל ילנה שבוחרים רק חלק מהתלמידים ולא את כולם. אני לא בדיוק יודע מה גורם לזה לעבוד לפעמים כן ולפעמים לא.
בכל מקרה, בחר את כולם לא עובד אף פעם אצלה וזו הבעיה המרכזית כרגע.

**Comment by Hermoni** [comment]
מידע נוסף אחרי בירורים שעשה שמוליק:
בשלב מסוים שמתי לב שכשאני בוחר חלק מהתלמידים לפעמים זה נקלט ולפעמים לא, ואח"כ שמתי לב שיש תלמיד אחד שלא מקבל יעדים. כל וריאציה שכוללת אותו לא פועלת, גם אם משבצים רק עבורו. אם לא כוללים אותו בשיבוץ היעד - זה עובד.
אח"כ בדקתי את התיאוריה אצל ילנה בכיתה הגדולה, ושם יש שלושה כאלה שעושים בעיות. אם מנטרלים אתם, כל השאר מקבלים את היעד.
כך שהבעיה היא ביוזרים של התלמידים. זה לא קשור לג'ימייל/פייסבוק כי גם בין המורים שרשומים כתלמידים שלי יש בעיה כזו וכולם נרשמו עם הג'ימייל שאני פתחתי להם.

תוכל לראות אצל ילנה עם התלמידים nikol, ofek, asaf.

**Comment by koreno** [comment]
בודק...

**Comment by koreno** [comment]
Should be fixed - please verify

**Comment by Hermoni** [comment]
עובד אצלי.
נתתי גם לשמוליק שיבדוק אצלו לוודא.
אגב, יש אפשרות להוסיף כפתור "הסר יעד" לכל התלמידים שמסומנים באופן פשוט יחסית מבחינתך?

**Comment by koreno** [comment]
לא מאוד מסובך, אבל מספיק בשביל שנפתח את זה כטיקט נפרד...
