### ISSUE TITLE
פיתוח - מערכת מעקב צפייה בסרטונים

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#63]
לשדרג את מערכת המעקב על צפייה בסרטונים משני מצבים "התחיל" ו"סיים" לסטטוסים נוספים שייתנו למורה יכולת לדעת כמה מהסרטון התלמיד צפה לפי כמות הנקודות שהוא צבר:
0-250 - התחיל לצפות
250-500 - צפייה חלקית
500-750 - צפה ברוב הסרטון
750 - סיים לצפות
לתת צבע לכל אחד מהסטטוסים שייראה התקדמות בדוחות המעקב.

**Comment by koreno** [comment]
http://testing.hebkhan.appspot.com/class_profile#/api/v1/user/students/progress/video_summary

**Comment by Hermoni** [comment]
אני חושב ששברת פה שיא במהירות פיתוח של משהו באתר :)
בכל מקרה, נראה מצוין כולל הצבעים.
להוסיף את החלוקה גם לדו"ח מצב (שם זה עדיין רק שני סטטוסים) ולהוסיף שם את המקרא של הצבעים.
אגב, לפי איזה מספרים חילקת את הסטטוסים?
חלק מהתלמידים שהיו בסטטוס "סיים לצפות" עבור לסטטוס "כמעט סיים" בסטטוסים החדשים.

**Comment by koreno** [comment]
עוד לא לגמרי סיימתי, אבל כן זה היה מהיר... :)
אני עדיין מתקן קצת עניינים פה כאן, זה איטי מידי ולא יעיל.
חילקתי לפי 1/3, 2/3. נראה שיש כאלה שהיו בקירוב לסיום ולכן הוצגו בסטטוס "סיים לצפות". אני אתקן כך שמי שצפה במעל ל-90% יחשב כ-"סיים לצפות".
אחרי מקצה השיפורים אפנה למסך דו"ח מצב.

תוכל לשכנע אותי אבל למה זה דרוש בדיוק? אני חושש שיש לזה עלות כלכלית בגוגל...

**Comment by Hermoni** [comment]
המורים נותנים לתלמידים לצפות בסרטונים לפני השיעורים ועוקבים אחרי הצפייה שלהם בתור שיעורי בית.
אם תלמיד צופה בסרטון ומדלג על חלקים ממנו או מריץ אותו במהירות גבוהה יותר, הוא לא יכול לצבור את 750 הנקודות ולכן הסטטוס שלו נשאר בתור "התחיל"
המטרה היא לספק למורים יותר מידע לגבי הצפייה בסרטונים של התלמידים שלהם כך שתלמיד שצפה ברוב הסרטון עדיין יוגדר בתור תלמיד שהכין שיעורי בית.
עד כמה העלות הכלכלית משמעותית?

**Comment by koreno** [comment]
אני אדע יותר טוב אחרי מקצה שיפורים

**Comment by koreno** [comment]
חלה התקדמות!
שיפרתי עניינים, זה אמור לעבוד יותר מהר.
כדי למנוע עלויות מיותרות הגבלתי את הרשימה לסרטים שנצפו בחודש האחרון - זה נשמע סביר? אפשר להגדיל את זה אם צריך.

**Comment by Hermoni** [comment]
נראה לי שחודש אחרון זה סביר. אם נראה שזה יוצר בעיות נשנה את זה אח"כ
בדקתי את זה עכשיו מול הגירסא הישנה ואני רואה שאתר test החיפוש ב"דוח מצב" לא עובד - שאני כותב נושא/סרטון מסוים הוא מציג לי אותו אבל לא מציג את התלמידים שצפו בו:
![image](https://cloud.githubusercontent.com/assets/8182787/5799488/986e5196-9fdb-11e4-9708-d6ca579b0eb5.png)
בכל מקרה, ב"סיכום מצב סרטונים" זה נראה מצוין. צריך גם להחיל את הצבעים והמקרא על "דוח מצב".

**Comment by koreno** [comment]
תיקנתי ועדכנתי, אני חושב שכמעט סיימתי.
אבל, המורה - גנבו לי את הלפטופ... אז אני לא יכול להמשיך להכין שיעורים!
ברצינות, נגנב לי היום התיק עם הלפטופ של העבודה, שמכיל את סביבת הפיתוח שלי עבור קהאן...
אני מקווה שיהיה לי חדש תוך יום-יומיים, אבל כנראה לא שאוכל לתקן עד אז.
בכל אופן תבדוק ותראה, ותרשום בדיוק מה עוד חסר/לא תקין.

**Comment by Hermoni** [comment]
אחלה של תירוץ :)
בכל מקרה, בדקתי את הדו"ח מצב וזה מופיע שם כמו שצריך.
משהו מוזר שקרה עכשיו בדו"ח זה המלבנים של שתלמידים שלא נכנסו בכלל לפעילות צבועים באפור במקום בלבן. המלבנים היחידים שבלבן הם "לא התחיל" אבל לא ברור לי מה ההבדל ביניהם לבין תלמידים שבכלל לא נכנסו לפעילות.
דוגמא לריבועים אפורים ולבנים:
![image](https://cloud.githubusercontent.com/assets/8182787/5888575/6652e632-a40d-11e4-94e7-4128551332e9.png)

**Comment by Hermoni** [comment]
אם אתה צריך שם משתמש וסיסמא לבדוק את זה:
liat.hebkhan
khan2014

**Comment by koreno** [comment]
Done!
