### ISSUE TITLE
מספר פתרונות להשגת מיומנות

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#65]
לפתח או למצוא אפשרות בהגדרות של תרגיל כך שהתלמיד מקבל מיומנות בו אחרי ניסיון אחד בלבד ולא לפי המודל הנוכחי כדי להחיל את האפשרות הזו על תרגילים בלי הגרלת מספרים.

**Comment by koreno** [comment]
you can now edit "Min. problems for proficiency" in the content admin screen for exercises. The default is 5 (although it might be a bit more if the the student has mistakes along the way). Reducing it to '1' should give you the behavior you're looking for.

Note - if you're changing this value for an existing exercise, students that have already started working on it will not be affected by this change. They will still be required to complete the exercise as before this change.

**Comment by koreno** [comment]
Also - you can use this screen to edit this value without having to publish the whole catalog:
http://www.hebrewkhan.org/admin94040

**Comment by Hermoni** [comment]
אני לא מוצא את האפשרות הזו בעמוד אדמין הרגיל ולא בעמוד אדמין תרגילים.

**Comment by koreno** [comment]
oh, right, it's in testing.hebkhan.appspot.com... :)

**Comment by Hermoni** [comment]
אני מניח שלאתר testing אין עמוד אדמין משלו אז נצטרך לבדוק את זה רק אחרי שהעדכונים יעלו לאתר הרגיל.
