### ISSUE TITLE
מערכת שיבוץ יעדים - הסרת יעדים באופן כללי

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#66]
להוסיף אפשרות להוריד מספר יעדים בבת אחת ע"י סימון כל היעדים הרלוונטיים ולחיצה על כפתור.
כרגע שבוחרים יעד מסוים זה בוחר את כל היעדים של אותו תלמיד אז יכול להיות שזה יצור בעיות שיימחקו יעדים מעבר לרצוי. אם זה באמת קורה אני לא בטוח אם באמת כדאי לפתח כפתור חדש כזה.

**Comment by koreno** [comment]
verify and close
testing.hebkhan.appspot.com/class_profile#/api/v1/user/students/goals
