### ISSUE TITLE
מערכת שיבוץ יעדים - היעלמות יעדים מהרשימה

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#67]
היעדים שהמורה שיבץ נעלמו מעמוד היעדים בממשק המורה שבוע לאחר שהוא שיבץ אותם.
אם נכנסים לתלמידים היעדים עדיין מופיעים אז כנראה העמוד מעלים יעדים שלא עבדו עליהם בשבוע האחרון.
לשנות כך שהיעדים תמיד יופיעו למורה בממשק מורה
מורה לדוגמא:
oshik.hebkhan
khan2014

**Comment by koreno** [comment]
בטיפול....

**Comment by koreno** [comment]
please verify and close
http://testing.hebkhan.appspot.com/

**Comment by Hermoni** [comment]
יש אפשרות להגדיל את טווח הזמן לבלתי מוגבל/ארוך מאוד או שזה ייצור בעיות חדשות?

**Comment by koreno** [comment]
בוא נתקדם עם זה, נגדיל אם וכאשר יהיה צורך. הכי טוב לאפשר למורה לכוון, אבל
זה מסובך קצת כרגע.
