### ISSUE TITLE
מערכת יעדים - תיקון באגים

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#68]
שמנסים ליצור יעד חדש כללי של חמישה סרטונים/תרגילים היעד מופיע בצורה חלקית בחלק העליון של המסך בלי פירוט השלבים ("כל תרגיל" / "כל סרטון") ובכל מקרה הוא לא נרשם במערכת כך שבסופו של דבר היעד לא נוצר. שבונים יעד מותאם אישית זה עובד כמו שצריך.
![image](https://cloud.githubusercontent.com/assets/8182787/6369111/cdc89964-bceb-11e4-86c1-489053bf32a2.png)
בנוסף, ביעד של חמישה סרטונים מופיע "כל תרגיל" במקום "כל סרטון" 
![image](https://cloud.githubusercontent.com/assets/8182787/6369128/e11953a0-bceb-11e4-957a-7ff13688ae2e.png)
ושמרחפים מעל 5 תרגילים, החלון מרחף נמצא מצד ימין כך שאם זזים אליו הוא נעלם
![image](https://cloud.githubusercontent.com/assets/8182787/6369141/020b9956-bcec-11e4-9dad-e5d5bd2fb80b.png)

**Comment by koreno** [comment]
please verify and close
http://testing.hebkhan.appspot.com/

**Comment by Hermoni** [comment]
הבאג של יצירת יעד חדש נפתר וגם הטעות כתיב ביצירת 5 סרטונים.
החלון של יצירת 5 תרגילים עדיין מרחף מצד ימין של היעד כך שאם זזים אליו הוא נעלם
![image](https://cloud.githubusercontent.com/assets/8182787/6655616/f60476ca-cb0d-11e4-9c6b-d6584ab22e07.png)

**Comment by koreno** [comment]
please verify and close
http://testing.hebkhan.appspot.com/
