### ISSUE TITLE
דו"ח פעילות יומי - זמן עבודה שלילי

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#72]
בממשק הדרכה בדו"ח פעילות יומי של המורה atara.hebkhan מופיעה תלמידה עם זמן פעילות שלילי ושמרחפים עליו רואים פעילות שלקחה לה 16 שנה!
שם משתמש  - atara.hebkhan
סיסמא - khan2014
היום הבעייתי - 08.03
![image](https://cloud.githubusercontent.com/assets/8182787/6555920/6082cd26-c672-11e4-838b-b82f46956ab0.png)

**Comment by koreno** [comment]
please verify and close
http://testing.hebkhan.appspot.com/
