### ISSUE TITLE
תיקון ניסוח

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#73]
אם מנסים להיכנס לממשק הדרכה לפני שמתחברים מתקבל המסך הבא:
![image](https://cloud.githubusercontent.com/assets/8182787/6555959/a0b79e62-c672-11e4-87f4-28cb9054cd82.png)
לתקן את הניסוח בשורה הראשונה את המילה "בחלק" ל"לחלק": "יש להתחבר לאתר כדי לגשת לחלק זה של האתר"

**Comment by koreno** [comment]
please verify and close
http://testing.hebkhan.appspot.com/
