### ISSUE TITLE
ממשק מורה - יעדים

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#74]
בממשק מורה בעמוד של יעדים המקרא צבעים מופיע לרגע כאשר טוענים את הדף ואח"כ הוא נעלם. שטוענים את הדף מחדש הוא מופיע קבוע משום מה.
![image](https://cloud.githubusercontent.com/assets/8182787/6663578/bf2745f6-cbd0-11e4-8394-4726083dc26a.png)
בנוסף, היעד נצבע בכחול כהה כאשר התלמיד סיים את היעד אבל אם נכנסים לתלמיד עצמו (לחיצה על השם שלו), הצבע כחול כהה מציין פעילות שלא הושלמה אז זה מבלבל את המורים.
דוגמא ליעד שהושלם (כחול כהה) ויעד בתהליך:
![image](https://cloud.githubusercontent.com/assets/8182787/6663632/474f5e82-cbd1-11e4-9b2c-3622ecfc1005.png)
אם נכנסים לאותו תלמיד אז הפעילות שהייתה כחולה (סיים) מופיעה בתכלת והפעילות שהוא טרם סיים (תכלת) מופיעה בכחול כהה 
![image](https://cloud.githubusercontent.com/assets/8182787/6663650/74d8e8be-cbd1-11e4-8b28-b27ea1aecbb8.png)

**Comment by koreno** [comment]
זה בצבעים שהתרגילים נצבעים בהם. אלא שהיעדים בשאר האתר צבועים הפוך...
זה יהיה לא עקבי איך שלא נעשה את זה, ואם נעשה את זה אחיד לכל האתר אז זה לא יהיה עקבי עם איך שזה היה בעבר...
עדיף לא לגעת לדעתי.
את המקרא אני אתקן.
(להבא בבקשה להפריד לטיקטים נפרדים)

**Comment by koreno** [comment]
verify and close
