### ISSUE TITLE
ממשק תלמיד - מסך פעילות - תיקון קישור

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#76]
שתלמיד בלי פעילויות נכנס למסך "פעילות" בפרופיל האישי שלו הוא מקבל את ההודעה הבאה:
![image](https://cloud.githubusercontent.com/assets/8182787/7104830/26207902-e103-11e4-91f4-779a2983efa9.png)
לחיצה על "נסו תרגיל" מובילה למפת הכוכבים.
צריך לתקן את הקישור שיוביל לקטלוג כמו שהקישור של "צפו בסרטון" עושה.

**Comment by koreno** [comment]
fixed
