### ISSUE TITLE
מערכת יעדים - שיבוץ קישור URL

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#77]
להוסיף אפשרות לשבץ כיעד את הפעילות שמובילות לקישורים חיצוניים.
כרגע שמנסים להוסיף אותה דרך מערכת היעדים מקבלים את השגיאה הבאה:
![image](https://cloud.githubusercontent.com/assets/8182787/7104881/30129460-e106-11e4-8202-1b59e2126c3c.png)
אפשר למצוא פעילויות כאלו ב"מתמטיקה תחילה (כיתה ט')-משוואות ריבועיות-אי שוויונים ריבועיים."

**Comment by koreno** [comment]
made progress!
Please check it out: testing.hebkhan.appspot.com

Make sure other goal types work as usual and that their display in the various screen (including the coaches screens) is correct.

**Comment by Hermoni** [comment]
עובד מצוין!
בדקתי גם יצירת יעד דרך תלמיד וגם יצירת יעד דרך מורה והכל עובד תקין משני הצדדים.
הבעיה היחידה שמצאתי היא שאחרי שהתלמיד משלים את היעד זה משנה את הסדר שלהם בממשק מורה:
ככה זה נראה אצל התלמיד:
![image](https://cloud.githubusercontent.com/assets/8182787/8271206/ad138052-1813-11e5-8534-d893a8fd8296.png)
ככה זה נראה בממשק מורה:
![image](https://cloud.githubusercontent.com/assets/8182787/8271209/ba372aa4-1813-11e5-8ca1-28f1e9a671b9.png)
אבל זה לא מרגיש לי ממש קריטי והייתי מעדיף שנמשיך הלאה.

**Comment by koreno** [comment]
מוזר.
זה קרה אי פעם אם סדר התרגילים והסרטים?

בכל אופן, אשמח אם נעשה שבוע-שבועיים הרצה עם כמה מורים לפני שנשחרר את זה לכולם.

**Comment by Hermoni** [comment]
זה לא קרה מקודם. זה גם מרכז את כל הקישורים בהתחלה. 
בכל מקרה, שנת הלימודים הסתיימה אז אין לנו דרך להריץ את זה עם המורים

**Comment by koreno** [comment]
טוב, אז אני אעלה לפרודקשן.
