### ISSUE TITLE
עמוד אדמין - יצירת נושאים עם רווח בשם

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#78]
אם יוצרים נושא חדש בעמוד אדמין עם רווח באמצע או בסוף זה תוקע את כל המערכת.
הפתרון זה אולי ליצור הודעה שקופצת שמנסים ליצור נושא עם רווח שמתריע על הבעיה לפני ששומרים את השינויים.

**Comment by koreno** [comment]
topic-ids should now automatically go lower-case and without spaces
