### ISSUE TITLE
דיווח תקלות במערכת התרגול

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#80]
אם משתמש פותח תקלה במערכת התרגול שזה יגיע גם לאתר של "יש בעיות" הכללי באתר כדי שהמשתמש יקליד את כתובת המייל שלו שנוכל לתקשר איתו אחר פתיחת התקלה להבין אותה לעומק.

**Comment by koreno** [comment]
דיווח תקלות יבצע מעתה דרך אותו ממשק של webengage.
אני עובד על הוספת מידע על התרגיל שהמשתמש נמצא בו, כרגע יש עם זה קצת בעיות...

**Comment by Hermoni** [comment]
עובד מצוין.
לסגור את זה או להשאיר לך פתוח בשביל הוספת המידע?

**Comment by koreno** [comment]
תשאיר פתוח, אני מחכה לתשובה מתמיכה של WebEngage

**Comment by Hermoni** [comment]
יש תשובה מהם?
