### ISSUE TITLE
דו"ח פעילות יומי - זמן עבודה שלילי

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#81]
זה שוב קרה לאחד התלמידים בזמן ששמוליק היה בכיתה והוא אומר שהמחשב של התלמיד נכבה באמצע הפעילות אז יכול להיות שזה מה שגורם לתקלה.
מדובר על הכיתה של נטשה - natasha.hebkhan
סיסמא -khan2014
![image](https://cloud.githubusercontent.com/assets/8182787/7488973/dec835ce-f3d9-11e4-8524-18a31bfaba30.png)

**Comment by koreno** [comment]
couldn't really find the source of this issue. I think that the clock on her computer somehow got reset while she was working. From some random checks in the database she was the only one with such a problem, so it doesn't seem like a major issue. I've added some code to the exercises program to prevent it from sending negative duration in the future.
