### ISSUE TITLE
שילוב לוגו העמותה

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#83]
לבקשתו של דרור, להכניס את הלוגו של העמותה לעמוד הראשי של האתר לצד הלוגו של קאהן
https://drive.google.com/open?id=0B1jJxDDw_yWLenhDVElnVS1ZYU0&authuser=0

**Comment by Hermoni** [comment]
ראיתי שדניל סיים את העבודה.
אפשר להעלות את זה לאתר?

**Comment by koreno** [comment]
האמת שלטעמי זה לא נראה טוב (ללא קשר לעבודה הטובה של דניל). אפשר להבין למה
זה חשוב? אולי אפשר להסתפק בהוספת הלוגו לאוסף למטה? לבנתיים?
אני חושב שאם רוצים לעשות את זה טוב צריך עיצוב גרפי קצת יותר מדויק...

**Comment by Hermoni** [comment]
תשובה מדרור:
עדיף בלי, או לשים אותו עם הלוגו למטה איפה שאני 10

**Comment by shalumovdanil** [comment]
אז מה המסכנה להוריד את הסמל למטה ?

**Comment by koreno** [comment]
לא דחוף. נראה לי שעדיף להתרכז בבעיות הממשק.
אני אבקש ממעצב להפוך את זה לאייקון תואם בנתיים.
