### ISSUE TITLE
עמוד פרופיל

### ISSUE THREAD

**Issue by Hermoni** [hebkhan/server#97]
במסך הפרופיל האישי של התלמידים במצב תקין תלמיד שלוחץ על "עריכת פרופיל" אמור לקבל חלון נפתח עם 4 אפשרויות שאחת מהם קריטית לתהליך הרישום - עריכת מידע אישי
![image](https://cloud.githubusercontent.com/assets/8182787/12816057/db22f6e2-cb52-11e5-8461-af787cd6526c.png)
חלק מהתלמידים דיווח שבפרופיל שלהם מופיעות רק שתי אפשרויות וזה מגביל את האפשרות שלהם לערוך את השם משתמש שלהם
![image](https://cloud.githubusercontent.com/assets/8182787/12816070/ef19040c-cb52-11e5-8fd2-367577f087ed.png)
ניסינו לבדוק מחשבים שונים עם משתמשים שונים ולא הצלחנו לשחזר בדיוק את הבעיה ולהבין ממה היא נגרמת.

**Comment by shalumovdanil** [comment]
אוקי אז ככה ,
הצלחתי לשחזר וניראה לי שאני מבין למה .
אז ככה שני האופציות נמצאות תחת תנאי של 
{{#if isFullyEditable}}
כאשר הערך הזה הוא 
var isFullyEditable = Profile.profile.get("isDataCollectible");
על משתנה 
isDataCollectible 
מצאתי את הדבר הבא 
  /**
     * Whether or not we can collect sensitive information like the user's
     * name. Users under 13 without parental consent should not be able
     * to enter data.
     */
מה שאומר שאם משתמש השתמש בחשבון 
FACEBOOK 
והוא פחות מ 13 אז הוא לא יוכל לשנות את את הפרטים האישיים .
אני עוד בודק 

רועי יש אפשרות לבדוק איך הם נכנסו למערכת ומה הגיל שלכם ? 

דניל

**Comment by Hermoni** [comment]
שלחתי מייל למנחה שתבדוק אם זה בכיתות שהיו בעיות.
ניסיתי לפתוח משתמש פייסבוק מתחת לגיל 13 אבל משום מה הוא לא מאפשר לי לפתוח אז אני לא יכול לבדוק את  זה אצלי.
בכל מקרה, התלמידים הם בכיתות ט-י אז הם אמורים להיות מעל גיל 13 גם אם נכנסו דרך פייסבוק.

**Comment by Hermoni** [comment]
יש אפשרות למחוק את הדרישה הזו שגם תלמידים עם חשבון פייסבוק מתחת לגיל 13 יוכלו לשנות פרטים אישיים?
תנסה לברר עם עופר לגבי זה

**Comment by shalumovdanil** [comment]
להוריד זה קל :)

השאלה עם אנחנו לא עוברים פה על חוק ?

דניל

2016-02-17 15:20 GMT+02:00 Hermoni <notifications@github.com>:

> יש אפשרות למחוק את הדרישה הזו שגם תלמידים עם חשבון פייסבוק מתחת לגיל 13
> יוכלו לשנות פרטים אישיים?
> תנסה לברר עם עופר לגבי זה
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hebkhan/server/issues/97#issuecomment-185202121>.
>



-- 
Danil Shalumov

**Comment by Hermoni** [comment]
אנחנו לא שואבים שום מידע מהמשתמש שלהם בפייסבוק ובכל מקרה כל המשתמשים שלנו בבתי ספר הם מעל גיל 13 אז אני לא רואה פה עבירה על החוק.
תוכל בבקשה להוריד את זה שנבדוק אם זה פותר את הבעיה?

**Comment by koreno** [comment]
מבחינתי סבבה - דניל אתה יודע איך להעביר לפרודקשן?

**Comment by shalumovdanil** [comment]
לא , עוד לא יצא לי.
אני יכול לעשות קלון מפרוד'שן ואחר כך פוש לגיד 
מה אתה אומר ?

**Comment by Hermoni** [comment]
יש חדש?

**Comment by shalumovdanil** [comment]
העלתי ברנץ עם תיקון , מחקה לעופר שיקח את התיקון

**Comment by koreno** [comment]
אני מסתכל על זה עכשיו

**Comment by koreno** [comment]
Done
